#pragma config(Sensor, S1,     Bumper1,        sensorTouch)
#pragma config(Sensor, S2,     IMU,            sensorI2CCustom9V)
#pragma config(Sensor, S4,     XBee,           sensorHighSpeed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S4,     ,               sensorHighSpeed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* xbee1 */

/* notes
	 115200
   xbee on PC source addr 4 dest 3 	panid 3332
   xbee on nxt source 3 dest 4 panid 3323

   1 touch
   2 dexter IMU
   4 xbee (485)

   */

#define WDS writeDebugStreamLine

TFileIOResult ior;

void TestPub()
{
	char *json = "PUBnxt/test,{\"data\":\"test123\"}\n";
	nxtWriteRawHS(json, strlen(json), 0);
}

void Test1Loop()
{
		while (true)
	{
		TestPub();
		wait1Msec(10);
	}
}

void Test2Loop()
{
		while (true)
	{
		int t = time1[T1];
		int ax, ay, az, tx, ty, tz, gx, gy, gz;

		//MSIMUreadAccelAxes(AIMU, ax, ay, az);
		//MSIMUreadTiltAxes(AIMU, tx, ty, tz);
		//MSIMUreadGyroAxes(AIMU, gx, gy, gz);

		TestPub();
		//dataLog(7, t, (az / 100.0));
		//dataLog(8, t, (tz / 1000.0));
		//dataLog(9, t, gz);

		wait1Msec(50);
	}
}

task main()
{
	clearDebugStream();
	writeDebugStreamLine("xbee.c");

	time1[T1] = 0;

	nxtEnableHSPort();            //Enable High Speed Port #4
	nxtSetHSBaudRate(57600);
	nxtHS_Mode = hsRawMode;       //Set to Raw Mode (vs. Master/Slave Mode)

	//Test1Loop();
	Test2Loop();



}
