#pragma config(Sensor, S1,     Bumper1,        sensorTouch)
#pragma config(Sensor, S2,     MSIMU,          sensorI2CCustomFastSkipStates)
#pragma config(Sensor, S4,     XBee,           sensorHighSpeed)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/mindsensors-imu.h"

/* xbee1 */

/* notes
115200
xbee on PC source addr 4 dest 3 	panid 3332
xbee on nxt source 3 dest 4 panid 3323

1 touch
2 Mindsensor Absolute IMU
4 xbee (485)

*/

#define WDS writeDebugStreamLine

void Test2Loop()
{
	while (true)
	{
		long x, y, z;
    MSIMUreadGyroAxes(MSIMU, x, y, z);

		char json[128];
		sprintf(json, "PUBnxt/Gyro,{\"x\":%f,\"y\":%f,\"z\":%f}\n", x, y, z);
		nxtWriteRawHS(json, strlen(json), 0);
		//WDS(json);
		wait1Msec(50);
	}
}

task main()
{
	clearDebugStream();
	writeDebugStreamLine("xbee.c");

	time1[T1] = 0;

	nxtEnableHSPort();            //Enable High Speed Port #4
	nxtSetHSBaudRate(57600);
	nxtHS_Mode = hsRawMode;       //Set to Raw Mode (vs. Master/Slave Mode)

	MSIMUsetGyroFilter(MSIMU, MSIMU_GYRO_FILTER_LEVEL_4);  // highest filtering
	delay(100);		// time for reconfigure

	Test2Loop();
}
